### ISSUE TITLE
Largeur des tronçons

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-mgb-platform#1]
Au niveau de la symbo des tronçons, on a dit que la largeur serait symbolisée en fonction de la largeur réelle du tronçon. Ou retrouver cette info  ? Dans le shapefile fourni par @AdrienOceanNext , je ne la vois pas

**Comment by jeanpommier** [comment]
Pardon, si, il y a bien un attribut width.

**Comment by AdrienHydroMatters** [comment]
Concernant la visu, ce qui marche pas trop mal pour moi (esthétiquement sur un sig...) c'est une largeur de 1 à 5 points, par classes de largeur: 
- de 0 à 100m
- de 100 à 500m
- de 500 à 1000m
- de 1000 à 2000m
- > 2000m
Veux-tu que je mette une nouvelle colonne dans le shapefile avec des valeurs de 1 à 5?

**Comment by jeanpommier** [comment]
Non non, pas besoin d'ajouter une nouvelle colonne, on va voir si on fait ça au niveau de la BD ou du frontend, mais l'info de largeur suffit.
Merci !
