### ISSUE TITLE
Limite géographique (emprise)

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-mgb-platform#3]
Il a été discuté de n'afficher que les tronçons inclus dans un secteur géographique donné. A priori un secteur plus complexe qu'une simple bounding box.
Pourriez-vous me donner cette emprise ? Le plus simple à maintenir est sans doute un shapefile, que je pourrai utiliser pour un filtre d'inclusion. Mais sinon, une liste d'IDs de tronçons peut aussi faire l'affaire.

**Comment by AdrienHydroMatters** [comment]
Jean, voici le shapefile de l'emprise A IGNORER. Dis moi si ce format te convient. 
[exclusion_mask.zip](https://github.com/OMP-IRD/hyfaa-mgb-platform/files/6182431/exclusion_mask.zip)

**Comment by jeanpommier** [comment]
Nickel. Je crois juste que tu as oublié un morceau (Nord Est) en dessinant l'emprise

**Comment by jeanpommier** [comment]
Je me suis permis de retoucher l'angle nord est. Mais il i a quand même quelques tracés qui sont un peu grossièrement impactés (couvert partiellement par la forme)
![image](https://user-images.githubusercontent.com/4491521/112013303-3cceb880-8b2a-11eb-962e-72bad2f1deeb.png)

Tu voudras peut-être affiner un peu le shapefile

**Comment by AdrienHydroMatters** [comment]
[exclusion_mask.zip](https://github.com/OMP-IRD/hyfaa-mgb-platform/files/6183324/exclusion_mask.zip)

Oui tu as raison. J'avais produit le masque à partir du réseau filtré avec le ordem>=10, donc j'étais large. Désolé. ça devrait être bon maintenant

**Comment by jeanpommier** [comment]
Nickel, merci
