### ISSUE TITLE
[tronçons] filtre sur attributs

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-mgb-platform#4]
@AdrienOceanNext tu avais d'ébord avancé qu'on pourrait filtrer les tronçons pour n'afficher que ceux ayant l'attribut ordem >=4. On a ensuite évoqué la possibilité d'un filtre plus avancé. 

Il faut donc qu'on précise ce filtre.

**Comment by AdrienHydroMatters** [comment]
On a testé visuellement, on n'affichera dans un premier temps que les tronçons pour lesquels l'attribut ORDEM >= 10
