### ISSUE TITLE
Données à transmettre pour affichage des minibassins

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-mgb-platform#5]
Pour l'affichage des minibassins, on a dit qu'on avait besoin, en termes de données, de :

- La largeur du tronçon
- Pour un affichage selon le débit : 
  - les valeurs de débit (on prend la valeur médiane), sur les 15 derniers jours
  - les dates correspondantes, bien sûr
- Pour un affichage selon l'anomalie : 
  - les dates
  - les valeurs d'anomalie, calculées avec
    - la moyenne
    - la variance
    - la valeur courante.

J'oublie quelque chose ?
La moyenne, je la détermine comment ? C'est la moyenne à un jour donné, sur l'ensemble des années ? La moyenne sur une plage de temps, glissante, autour du jour concerné, la moyenne sur l'ensemble de toutes les valeurs dispos sur ce minibassin ?
Quelle est la formule permettant de calculer l'anomalie ?
Le plus simple sera probablement d'implémenter ces calculs au niveau de la base de données, si j'y dispose des informations suffisantes.

**Comment by AdrienHydroMatters** [comment]
Pour la moyenne, il faudrait qu'elle soit calculée sur le long terme (moyenne long terme pour chaque tronçon), donc ça dépend de la durée de simus qu'il y a dans la bd. J'ai cru comprendre qu'il vaut mieux ne pas trop stocker dans la bd pour ne pas causer de pb de perf, donc on n'aura certainement pas > 5 ans. Dans ce cas, ne vaut-il pas mieux qu'on le calcule a priori et ajoute la colonne dans le shapefile, quitte à faire une mise à jour par an pour prendre en compte l'année écoulée
Pour l'annomalie je voyais quelque chose de simple: (Debit(jour j) - DebitMoy) / DebitMoy x 100
Quelle est la meilleure solution pour toi?

**Comment by jeanpommier** [comment]
Je ne pense pas que stocker 10 ans de données en BD soit un problème. Surtout que les données sont allégées, et j'optimise le type des valeurs pour réduire l'encombrement. Ensuite, c'est surtout une affaire de bien configurer la BD, c'est pour ça que je prends mon temps : selon les données à stocker, il y a des choses que je ne fais pas pareil.

Perso, j'aurais tendance à utiliser la BD pour le calcul de la moyenne. Ca n'impactera pas la performance, car le calcul de moyenne n'a besoin d'être fait qu'une fois par jour (et encore), quand on ajoute des données. Ensuite, je le stocke en base jusqu'à la mise à jour suivante, pas de souci.
La formule de calcul de l'anomalie est simple. Je ferai tous les calculs en même temps (moyenne, anomalies), dans la BD.

Du coup, je clos le ticket. Merci !

**Comment by AdrienHydroMatters** [comment]
Parfait, efficace once again :)
