### ISSUE TITLE
MAD

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-mgb-platform#6]
@AdrienOceanNext comme je sais que tu aimes être sollicité ;o), j'aurais besoin d'un rappel de ce qu'on fait avec la MAD. Et, globalement, de faire un point sur les données transférées pour l'affichage dans un graphique.

Si je me souviens bien, la MAD intervient dans le graphique (suite à clic sur une station). L'idée étant de fournir un "encadrement" des valeurs standard du débit : moyenne +- MAD. C'est ça ?

On parle toujours de la moyenne globale, à long terme, la même que https://github.com/OMP-IRD/hyfaa-mgb-platform/issues/5 ?
Je la calcule sur le modèle avec assimilation ?

Donc, si je récapitule, pour le graphique, j'envoie : 
- données avec assimilation
  - le débit avec assimilation
  - la MAD
  - la moyenne globale (calculée sur le modèle avec assimilation)
- données sans assimilation
  - la moyenne
- prévis
  - les n trajectoires de prévision

Et par défaut, je n'envoie que la dernière année de données. Si besoin, on pourra spécifier la plage temporelle, y compris demander tout l'historique.

J'ai tout bon ?

**Comment by AdrienHydroMatters** [comment]
"Si je me souviens bien, la MAD intervient dans le graphique (suite à clic sur une station). L'idée étant de fournir un "encadrement" des valeurs standard du débit : moyenne +- MAD. C'est ça ?"
en fait cette MAD sur le run avec assim c'est pour illustrer la dispersion des ensembles du run, donc elle est calculée sur les débits des différents ensembles au jour j sur chaque tronçon (et non plus sur la série temporelle des débits sur le tronçon en question). Idem pour cette moyenne, en fait celle que tu affiches au clic sur une station c'est la moyenne des ensembles, et non des jours, comme celle que tu as en code couleur. Mais si j'ai bien compris c'est ce qu'il y a dans le ncdf non?)

Donc, si je récapitule, pour le graphique, **tu** envoie :

- données avec assimilation
        le débit avec assimilation **(si c'est ce qui sort dans le ncdf, ça correspond à la moyenne des n ensembles)**
        la MAD
        la moyenne globale (calculée sur le modèle avec assimilation) **-je ne crois pas qu'on l'aie discuté ça, si? En fait la seule chose qui aurait du sens ici c'est d'afficher une moyenne journalière (calculer pour chaque jour de l'année et pour chaque tronçon la valeur moyenne de débit à partir de la bdd passée), mais on n'en a jamais parlé-**
- données sans assimilation
        **le débit sans assim**
- prévis
        les n trajectoires de prévision

Je ne sais pas si c'est clair... on itère :) Il faut peut être que je reprenne ton CR aussi..

**Comment by jeanpommier** [comment]
- débit avec assimilation : on avait dit la médiane, pas la moyenne, je crois
- débit sans assim : Rémi l'a appelé moyenne. Mais dans tous les cas, je n'ai qu'une donnée, donc j'envoie celle-ci
- Pour ce qui est de la MAD, si je me souviens bien, elle a été évoquée quand vous suggériez d'afficher en fond grisé la plage de valeurs "normales" , de type moyenne +/- écart type. Et vous aviez conclu qu'il vaudrait mieux utiliser la MAD. Du coup, il faut qu'on précise ce qui sert à déterminer cette plage grisée. Dans tous les cas, pour ce qui me concerne, c'est des données assez facile à produire à partir de ce que j'ai récupéré en BD, il faut juste qu'on précise quoi. Par exemple, la moyenne journalière, c'est assez facile à calculer, moyennant possiblement un décalage d'un jour sur les années bissextiles.

**Comment by jeanpommier** [comment]
Mais je complique peut-être les choses. En relisant, je me dis que ce que tu voulais, c'est peut-être simplement déterminer la plage grise via la valeur du jour +/- la MAD

**Comment by AdrienHydroMatters** [comment]
oui c'est ça pour la plage de valeurs grisée (médiane +/- MAD). Pour la moyenne journalière à la rigueur peu importe s'il y a un décalage d'un jour sur certaines années, c'est indicatif. ça ferait une courbe de plus (disons bande grisée, courbe continue -médiane des Q assim- d'une couleur et courbe pointillée d'une autre couleur pour cette moyenne journalière)

**Comment by jeanpommier** [comment]
OK, pour la plage de valeurs grisée.
Moyenne journalière, tu la veux, du coup ? Peut-être que ça risque d'encombrer la lecture. Mais c'est pas un pb, de mon côté, pour rajouter la possibilité

**Comment by AdrienHydroMatters** [comment]
Allez si c'est bon pour toi j'achète :), j'avais la même inquiétude que toi sur l'encombrement, mais avoir un guide "une année normale est comme ça" est utile je pense. On verra à l'utilisation
